package com.szabist.zabcafe.ui.screens

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.Button
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.szabist.zabcafe.model.Order
import com.szabist.zabcafe.viewmodel.CartViewModel
import com.szabist.zabcafe.viewmodel.OrderViewModel

@Composable
fun CheckoutScreen(
    cartViewModel: CartViewModel,
    orderViewModel: OrderViewModel,
    onOrderPlaced: () -> Unit
) {
    val cartItems by cartViewModel.cartItems.collectAsState()
    val totalCost by cartViewModel.totalCost.collectAsState()

    Column(modifier = Modifier.fillMaxSize().padding(16.dp)) {
        Text("Checkout", fontSize = 24.sp, modifier = Modifier.padding(bottom = 16.dp))

        LazyColumn(modifier = Modifier.weight(1f)) {
            items(cartItems) { cartItem ->
                CheckoutItemComponent(cartItem)
            }
        }

        Spacer(modifier = Modifier.height(16.dp))

        Text("Total: $${totalCost}", fontSize = 20.sp, fontWeight = FontWeight.Bold, modifier = Modifier.align(Alignment.End))

        Spacer(modifier = Modifier.height(16.dp))

        Button(
            onClick = {
                val order = Order(
                    orderId = "",  // This will be generated by Firebase
                    userId = "currentUserId",  // Replace with the actual user ID
                    items = cartItems,
                    totalCost = totalCost,
                    status = Order.OrderStatus.PENDING
                )
                orderViewModel.createOrder(order)
                onOrderPlaced()
            },
            modifier = Modifier.fillMaxWidth()
        ) {
            Text("Place Order")
        }
    }
}

@Composable
fun CheckoutItemComponent(cartItem: Order.OrderItem) {
    Row(modifier = Modifier.fillMaxWidth().padding(vertical = 8.dp), verticalAlignment = Alignment.CenterVertically) {
        Column(modifier = Modifier.weight(1f)) {
            Text(cartItem.itemName, fontSize = 18.sp, fontWeight = FontWeight.Bold)
            Text("Quantity: ${cartItem.quantity}", fontSize = 16.sp)
            Text("Price: $${cartItem.price * cartItem.quantity}", fontSize = 16.sp, color = MaterialTheme.colorScheme.primary)
        }
    }
}